# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'Just testing'
url:                 http://lanyon.getpoole.com
baseurl:             'http://nikwek.github.io/lanyon/'
paginate:            5

# About/contact
author:
  name:              Nik Wekwerth
  url:               https://twitter.com/nwekwerth
  email:             nik.wekwerth@gmail.com

# Custom vars
version:             1.0.0
