# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Lanyon
tagline:          'A Jekyll theme'
description:      'Just Testing'
url:              http://lanyon.getpoole.com
baseurl:          http://nikwek.github.io/lanyon/

author:
  name:           'Nik Wekwerth'
  url:            https://twitter.com/nwekwerth

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/nikwek/lanyon
