# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'Librato Documentation'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nik Wekwerth
  url:               https://twitter.com/nwekwerth
  email:             nik.wekwerth@gmail.com

# Custom vars
version:             1.0.0

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
